# Generated by Django 3.2.18 on 2023-04-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100)),
                ('descripcion', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.TextField(max_length=100)),
                ('titulo', models.TextField(max_length=200)),
                ('cuerpo', models.TextField(max_length=1000)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100)),
                ('usuario', models.TextField(max_length=100)),
                ('contrasena', models.TextField(max_length=100)),
                ('grupo', models.TextField(max_length=100)),
                ('fecha_nacimiento', models.DateField(verbose_name='%d-%m-%Y')),
            ],
        ),
    ]
